Fix build on v5.17: implicit declaration of function ‘PDE_DATA’
PDE_DATA is unprovided in 359745d78351c ("proc: remove PDE_DATA()
completely"). Error message:

    CC [M]  xt_ratelimit.o
  xt_ratelimit.c: In function ‘ratelimit_proc_open’:
  xt_ratelimit.c:318:17: error: implicit declaration of function ‘PDE_DATA’ [-Werror=implicit-function-declaration]
     sf->private = PDE_DATA(inode);
		   ^~~~~~~~